"""add payroll fields

Revision ID: 013
Revises: 012
Create Date: 2026-08-05 16:06:27.680130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '013'
down_revision: Union[str, None] = '012'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('branch_code', sa.String(length=50), nullable=True))
    op.add_column('employees', sa.Column('earned_basic', sa.Float(), nullable=True))
    op.add_column('employees', sa.Column('earned_hra', sa.Float(), nullable=True))
    op.add_column('employees', sa.Column('earned_lta', sa.Float(), nullable=True))
    op.add_column('employees', sa.Column('earned_other_allowance', sa.Float(), nullable=True))
    op.add_column('employees', sa.Column('earned_actual_gross', sa.Float(), nullable=True))
    op.add_column('employees', sa.Column('attendance_bonus', sa.Float(), nullable=True))
    op.add_column('employees', sa.Column('odw', sa.Float(), nullable=True))
    op.add_column('employees', sa.Column('internet_charges', sa.Float(), nullable=True))
    op.add_column('employees', sa.Column('salary_advance', sa.Float(), nullable=True))
    op.add_column('employees', sa.Column('pf_wage', sa.Float(), nullable=True))
    op.add_column('employees', sa.Column('earned_pf_wage', sa.Float(), nullable=True))
    op.add_column('employees', sa.Column('pf_ded_employee', sa.Float(), nullable=True))
    op.add_column('employees', sa.Column('pf_ded_employer', sa.Float(), nullable=True))
    op.add_column('employees', sa.Column('vpf', sa.Float(), nullable=True))
    op.add_column('employees', sa.Column('pf_vpf_employee', sa.Float(), nullable=True))
    op.add_column('employees', sa.Column('esi_ded_employee', sa.Float(), nullable=True))
    op.add_column('employees', sa.Column('esi_ded_employer', sa.Float(), nullable=True))
    op.add_column('employees', sa.Column('tds', sa.Float(), nullable=True))
    op.add_column('employees', sa.Column('pt', sa.Float(), nullable=True))
    op.add_column('employees', sa.Column('lwf', sa.Float(), nullable=True))
    op.add_column('employees', sa.Column('other_deduction', sa.Float(), nullable=True))
    op.add_column('employees', sa.Column('total_deduction', sa.Float(), nullable=True))
    op.add_column('employees', sa.Column('eps_wage', sa.Float(), nullable=True))
    op.add_column('employees', sa.Column('pf_833', sa.Float(), nullable=True))
    op.add_column('employees', sa.Column('pf_367', sa.Float(), nullable=True))
    op.add_column('employees', sa.Column('esi_050', sa.Float(), nullable=True))
    op.add_column('employees', sa.Column('esi_050_employer', sa.Float(), nullable=True))
    op.add_column('employees', sa.Column('edli_001', sa.Float(), nullable=True))
    op.add_column('employees', sa.Column('bonus', sa.Float(), nullable=True))
    op.alter_column('leave_requests', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text("timezone('utc'::text, now())"))
    op.alter_column('shift_requests', 'employee_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Integer(),
               existing_nullable=False,
               postgresql_using="employee_id::integer")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shift_requests', 'employee_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('leave_requests', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text("timezone('utc'::text, now())"))
    op.drop_column('employees', 'bonus')
    op.drop_column('employees', 'edli_001')
    op.drop_column('employees', 'esi_050_employer')
    op.drop_column('employees', 'esi_050')
    op.drop_column('employees', 'pf_367')
    op.drop_column('employees', 'pf_833')
    op.drop_column('employees', 'eps_wage')
    op.drop_column('employees', 'total_deduction')
    op.drop_column('employees', 'other_deduction')
    op.drop_column('employees', 'lwf')
    op.drop_column('employees', 'pt')
    op.drop_column('employees', 'tds')
    op.drop_column('employees', 'esi_ded_employer')
    op.drop_column('employees', 'esi_ded_employee')
    op.drop_column('employees', 'pf_vpf_employee')
    op.drop_column('employees', 'vpf')
    op.drop_column('employees', 'pf_ded_employer')
    op.drop_column('employees', 'pf_ded_employee')
    op.drop_column('employees', 'earned_pf_wage')
    op.drop_column('employees', 'pf_wage')
    op.drop_column('employees', 'salary_advance')
    op.drop_column('employees', 'internet_charges')
    op.drop_column('employees', 'odw')
    op.drop_column('employees', 'attendance_bonus')
    op.drop_column('employees', 'earned_actual_gross')
    op.drop_column('employees', 'earned_other_allowance')
    op.drop_column('employees', 'earned_lta')
    op.drop_column('employees', 'earned_hra')
    op.drop_column('employees', 'earned_basic')
    op.drop_column('employees', 'branch_code')
    # ### end Alembic commands ###
