"""add manager_comment to leave_requests

Revision ID: 399fee761905
Revises: 256d59a2b81c
Create Date: 2026-07-24 15:18:53.553567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '399fee761905'
down_revision: Union[str, None] = '256d59a2b81c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attendance', 'employee_reply')
    op.drop_column('attendance', 'clarification_reason')
    op.add_column('leave_requests', sa.Column('manager_comment', sa.Text(), nullable=True))
    op.alter_column('users', 'seen_announcement_ids',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'seen_announcement_ids',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.drop_column('leave_requests', 'manager_comment')
    op.add_column('attendance', sa.Column('clarification_reason', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('attendance', sa.Column('employee_reply', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
