"""Add employee performance table

Revision ID: 3d2ffc3a8067
Revises: None
Create Date: 2026-07-21 18:02:45.431527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d2ffc3a8067'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'summary')
    op.alter_column('leave_policies', 'applicable_gender',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'All'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('leave_policies', 'applicable_gender',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'All'::character varying"))
    op.add_column('employees', sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
